.PHONY: insert-fake-books-in-queue
INSTALL_CMD=python3 -m pip install --user -r requirements.txt
RUN_CMD=python3 main.py

insert-fake-books-in-queue:
	cd insert-fake-books-in-queue && $(INSTALL_CMD) && $(RUN_CMD)
