version: '3'

services:
  app:
    image: ghcr.io/jeremychauvet/terraform:0.14.7
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace
      - ${HOME}/.aws/credentials:/home/vhugo/.aws/credentials
      - ${HOME}/.ssh/:/home/vhugo/.ssh/
    command: tail -f /dev/null
