name: Publish front to S3.
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.1.0

        - name: Install dependencies
          run: cd web && make install

        - name: Build
          run: cd web && make build

        - name: Deploy
          uses: jakejarvis/s3-sync-action@master
          with:
            SOURCE_DIR: web/dist/*
            AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-east-1
