name: Publish front to S3.
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: cd web && make install

        - name: Build
          run: cd web && make install

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: web/dist/*
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: us-east-1
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
